# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-10 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
