# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, db_column='names', on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
    ]
