# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20191011_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(db_column='names', on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
    ]
